AVAILABLE_GRID_SIZES = [10, 20, 50]
DEFAULT_GRID_SIZE = 20
WINDOW_SIZE = 7
SNAKE_INITIAL_LENGTH = 3
NUM_SAMPLES = {10: 10000, 20: 20000, 50: 50000}
INPUT_FEATURES = WINDOW_SIZE * WINDOW_SIZE + 2  # 51

EPOCHS = 100
BATCH_SIZE = 32
VALIDATION_SPLIT = 0.2
PATIENCE_EARLY_STOP = 10
LEARNING_RATE = 0.001

BENCHMARK_NUM_GAMES = 50
CELL_SIZE = 30
FPS = 10

BASE_DIR = "."
DATA_RAW_DIR = "data/raw"
DATA_PROCESSED_DIR = "data/processed"
MODELS_DIR = "models"
RESULTS_DIR = "results"
PLOTS_DIR = "results/plots"
LOGS_DIR = "results/logs"
REPORTS_DIR = "results/reports"